server:
  port: 8085
  mode : debug
  log_level: debug

kafka:
  connection:
    brokers: 
      - localhost:19092
  topics:
    default-producer: test.output
    default-consumer: test.input
    default-consumer-group: test.group
